// gamesData.ts
const games = [
  {
    id: "1",
    title: "Cyber Nexus",
    imageUrl: "/placeholder.svg",
    rating: 4.8,
    releaseYear: 2024,
    genre: "Sci-Fi RPG",
    developer: "Future Games",
  },
  {
    id: "2",
    title: "Stellar Odyssey",
    imageUrl: "/placeholder.svg",
    rating: 4.5,
    releaseYear: 2024,
    genre: "Space Exploration",
    developer: "Cosmic Studios",
  },
  {
    id: "3",
    title: "Neon Samurai",
    imageUrl: "/placeholder.svg",
    rating: 4.2,
    releaseYear: 2024,
    genre: "Cyberpunk Action",
    developer: "Neon Forge",
  },
  {
    id: "4",
    title: "Quantum Breach",
    imageUrl: "/placeholder.svg",
    rating: 4.9,
    releaseYear: 2024,
    genre: "Quantum Thriller",
    developer: "Q-Bit Games",
  },
  {
    id: "5",
    title: "Ethereal Realms",
    imageUrl: "/placeholder.svg",
    rating: 4.6,
    releaseYear: 2024,
    genre: "Fantasy MMO",
    developer: "Mystic Worlds",
  },
  {
    id: "6",
    title: "Void Explorers",
    imageUrl: "/placeholder.svg",
    rating: 4.1,
    releaseYear: 2023,
    genre: "Space Sim",
    developer: "Nebula Interactive",
  },
  {
    id: "7",
    title: "Chrono Shift",
    imageUrl: "/placeholder.svg",
    rating: 4.7,
    releaseYear: 2023,
    genre: "Time Travel Adventure",
    developer: "Temporal Games",
  },
  {
    id: "8",
    title: "Nebula Warriors",
    imageUrl: "/placeholder.svg",
    rating: 4.4,
    releaseYear: 2023,
    genre: "Sci-Fi Strategy",
    developer: "Galactic Forge",
  },
  {
    id: "9",
    title: "Synthwave Racer",
    imageUrl: "/placeholder.svg",
    rating: 4.3,
    releaseYear: 2023,
    genre: "Retro Racing",
    developer: "80s Pixel Studio",
  },
  {
    id: "10",
    title: "Dark Echo",
    imageUrl: "/placeholder.svg",
    rating: 4.5,
    releaseYear: 2023,
    genre: "Horror Puzzle",
    developer: "Shadow Games",
  },
  {
    id: "11",
    title: "Astral Legacy",
    imageUrl: "/placeholder.svg",
    rating: 4.9,
    releaseYear: 2022,
    genre: "Space Opera RPG",
    developer: "Starborn Studios",
  },
  {
    id: "12",
    title: "Cyber Knights",
    imageUrl: "/placeholder.svg",
    rating: 4.8,
    releaseYear: 2022,
    genre: "Cyberpunk Tactics",
    developer: "Neon Samurai Inc.",
  },
  {
    id: "13",
    title: "Neo Dynasty",
    imageUrl: "/placeholder.svg",
    rating: 4.8,
    releaseYear: 2022,
    genre: "Futuristic Strategy",
    developer: "Quantum Forge",
  },
  {
    id: "14",
    title: "Quantum Wars",
    imageUrl: "/placeholder.svg",
    rating: 4.7,
    releaseYear: 2022,
    genre: "Sci-Fi Shooter",
    developer: "Particle Games",
  },
  {
    id: "15",
    title: "Solar Empire",
    imageUrl: "/placeholder.svg",
    rating: 4.7,
    releaseYear: 2022,
    genre: "Space 4X",
    developer: "Cosmic Strategies",
  },
];

export default games;
